### ISSUE TITLE
Relevance to reflex-0.5 is unclear

### ISSUE THREAD

**Issue by deepfire** [reflex-frp/reflex-examples#13]
How much relevance do the examples bear for the soon-to-be released version 0.5?

**Comment by ali-abrar** [comment]
They'll need to be updated. Some of them are out of date because of changes to reflex(-dom) and some are out of date because of changes to ghcjs-dom/jsaddle-dom.

**Comment by gspia** [comment]
Hi, have a look at the [same set + extras](https://github.com/gspia/reflex-examples). I'd be happy if the updated ones there could be merged into this official example set and especially, if somebody could give a bit more (there are things/techniques that could be elaborated with relatively short examples, which in turn, would help everybody new to rfp to get some learning speed).

**Comment by dfordivam** [comment]
@gspia I think it would be good to merge your updated examples into this repo.
I am also thinking of removing https://github.com/reflex-frp/reflex-frp.org/tree/master/code-snippets and instead refer to examples in this repo from the docs directly.

**Comment by ali-abrar** [comment]
All of the examples have been updated to a fairly recent version of reflex(-dom). I'm going to close this issue for now, but please reopen if something requires resolution.
