### ISSUE TITLE
Instruction is unclear

### ISSUE THREAD

**Issue by cblp** [reflex-frp/reflex-examples#19]
`ob run` stops with
```
Ok, 19 modules loaded.
Loaded GHCi configuration from /run/user/1000/ob-ghci-ea5f1d2755776854/.ghci
```

What next?

**Comment by luigy** [comment]
After that there should have been some text like bellow, but it looks like something else may have failed.
```
Running test...


Frontend running on http://localhost:8000/
```
I wonder if port `8000` is already taken and the error message is not being displayed properly here

**Comment by ali-abrar** [comment]
@cblp Are you still encountering this issue?

**Comment by cblp** [comment]
Now it works, thanks!

**Comment by ali-abrar** [comment]
Great to hear!
